# This workflow assigns our default project to new pull requests
name: Assign new PRs to default project's "In Progress" column
on:
  pull_request:
    types: [opened]

jobs:
  add-new-pr-to-project-column:
    runs-on: ubuntu-latest
    steps:
    - name: assign-new-pr-to-project
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/lyne-design-system/lyne/projects/1
        GITHUB_PROJECT_COLUMN_NAME: In progress
